### ISSUE TITLE
Nit: remove the comment

### ISSUE THREAD

**Issue by FarhadHashimov** [evmos/testing#22]
Nit: remove the comment
```suggestion
```

_Originally posted by @GAtom22 in https://github.com/evmos/testing/pull/17#discussion_r1164042243_
            
```[tasklist]
### Tasks
- [ ] https://github.com/evmos/testing/pull/24
- [ ] https://github.com/evmos/testing/pull/21
- [ ] https://github.com/evmos/testing/pull/18
- [ ] https://github.com/evmos/testing/pull/19
- [ ] https://github.com/evmos/testing/pull/17
- [ ] https://github.com/evmos/testing/pull/14
- [ ] https://github.com/evmos/testing/pull/13
```

**Comment by FarhadHashimov** [comment]
> ```
>           Nit: remove the comment
> ```
> 
> _Originally posted by @GAtom22 in [#17 (comment)](https://github.com/evmos/testing/pull/17#discussion_r1164042243)_

**Comment by FarhadHashimov** [comment]
https://github.com/evmos/testing/issues/22#issuecomment-1731652771

**Comment by FarhadHashimov** [comment]
https://github.com/evmos/testing/issues/22#issuecomment-1731653925

**Comment by FarhadHashimov** [comment]
Salam

**Comment by FarhadHashimov** [comment]
(https://github.com/evmos/testing/issues/22#issuecomment-1731657634)

**Comment by FarhadHashimov** [comment]
Salam

**Comment by FarhadHashimov** [comment]
Salam
